name: Actualizar EPG Comprimido

on:
  schedule:
    - cron: '0 0 */3 * *' # Se ejecuta cada 3 días a medianoche
  workflow_dispatch: # Permite ejecutarlo a mano desde Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar script de filtrado y compresión
        run: python script.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Añadimos el nuevo archivo .gz y el script
          git add alvaroguia.xml.gz
          git commit -m "EPG comprimido actualizado" || exit 0
          git push
